- name: Remove default nginx html
  file:
    path: /var/www/html/*
    state: absent
  become: yes

- name: Copy React build to nginx folder
  copy:
    src: /home/trongtin24521790/my-projects/devops-ansible/deploy/build/
    dest: "{{ deploy_path }}"
  become: yes
