- name: Remove default nginx html
  file:
    path: /var/www/html/*
    state: absent
  become: yes

- name: Copy React build to nginx folder
  copy:
    src: "{{ playbook_dir }}/../deploy/build/"
    dest: "{{ deploy_path }}"
  become: yes
