- name: Remove default nginx html
  file:
    path: /var/www/html/*
    state: absent
  become: yes

- name: Copy React build to nginx folder
  copy:
    src: /home/trung/devops-ansible/deploy/build/
    dest: /var/www/html/
  become: yes
