- name: Install nginx (RHEL/Amazon Linux)
  yum:
    name: nginx
    state: present
    update_cache: yes
  become: yes
  when: ansible_os_family in ["RedHat"]

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Configure nginx (Amazon Linux 2)
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  become: yes
  when: ansible_os_family in ["RedHat"]
