- name: Install required packages
  yum:
    name:
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes
  become: yes

- name: Install Docker
  yum:
    name: docker.io
    state: present
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
