name: Build & Deploy to AWS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build React
        run: |
          cd frontend
          npm install
          npm run build

      - name: Prepare directory on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/devops-ansible/deploy

      - name: Copy build to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "frontend/build/*"
          target: "/home/ubuntu/devops-ansible/deploy/"

      - name: Deploy with Ansible
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/ubuntu/devops-ansible
            git pull
            cd ansible
            ansible-playbook -i inventory.ini site.yml
